# used for kitten & doggy, forever.

[github]
id = "kitten030doggy"
link = "https://github.com/kitten030doggy"
account = "<gmail.email>"
passwd = "6 lower letter + 3 number digit, {meow's name}{woof's name}{某位技师的id}"

[gmail]
email = "kitten.030.doggy@gmail.com" 

