# used for kitten & doggy, forever.

[github]
id = "kitten030doggy"
link = "https://github.com/kitten030doggy"
account = "kitten.030.doggy@gmail.com"
passwd = "ljlgsq137"

[gmail]
email = "kitten.030.doggy@gmail.com" 

